media:
  input: public/images
  output: /images

components:
  alignment:
    type: select
    label: Ausrichtung
    options:
      values:
        - value: left
          label: Linksbündig
        - value: centered
          label: Zentriert
        - value: right
          label: Rechtsbündig
content:
  - name: pages
    label: Seiten
    type: collection
    path: content/pages
    filename:
      template: "{title}.md"
      field: true
    fields:
      - name: title
        label: Titel
        type: string
        required: true

      - name: lead
        label: Vorspann
        type: rich-text
        
      - name: content
        label: Inhalt
        type: block
        list: true
        blockKey: type
        blocks:
          - name: sectionTitle
            label: Überschrift 1
            fields:
              - name: text
                type: string
                required: true
              - name: alignment
                component: alignment
              
          - name: subsectionTitle
            label: Überschrift 2
            fields:
              - name: text
                type: string
                required: true
          - name: paragraph
            label: Fließtext
            fields:
              - name: text
                type: rich-text
                required: true
          - name: image
            label: Bild
            fields:
              - name: src
                type: image
                required: true
              - name: alt
                type: string
                required: true
              - name: alignment
                label: Ausrichtung
                component: alignment
              - name: textWrap
                label: Textfluss
                type: select
                options:
                  values:
                    - value: aboveAndBelow
                      label: Oberhalb und unterhalb
                    - value: around
                      label: Text umfließt das Bild
                    - value: none
                      label: Kein Textfluss

  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: siteSettings
    label: Site settings
    type: file
    path: src/_data/site.json
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: url
        type: string
  - name: docs
    label: Docs
    type: group
    items:
      - name: docsPages
        label: Docs Pages
        type: collection
        path: content/docsPages
        fields:
          - name: title
            type: string

      - name: references
        label: References
        type: group
        items:
          - name: publications
            label: Publications
            type: file
            path: data/publications.json
            format: json
            list: true
            fields:
              - name: title
                type: string
              
actions:
  - name: deploy-site
    label: Deploy site
    workflow: pages-cms-action.yml
