media:
  input: src/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: site
    label: Site settings
    type: file
    path: src/_data/site.json
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: url
        type: string
  - name: docs
    label: Docs
    type: group
    items:
      - name: pages
        label: Pages
        type: collection
        path: content/pages
        fields:
          - name: title
            type: string

      - name: references
        label: References
        type: group
        items:
          - name: publications
            label: Publications
            type: file
            path: data/publications.json
            format: json
            list: true
            fields:
              - name: title
                type: string
      - name: blockstuff
        label: Try the Block
        type: collection
        path: content/blockstuff
        fields:
          - name: oita
            label: Oita
            type: block
            list: true
            blockKey: type
            blocks:
              - name: hero
                fields:
                  - name: heading
                    type: string
                  - name: image
                    type: image
  
              - name: text
                fields:
                  - name: body
                    type: rich-text
              
actions:
  - name: deploy-site
    label: Deploy site
    workflow: pages-cms-action.yml
